;METADATA=(Diff=true, UseCommands=true)
[/Script/FortniteGame.FortGameUserSettings]
FullscreenMode=0
CosmeticStreamingEnabled=CodeSet_Enabled
FortniteReleaseVersion=13
UnlockConsoleFPS=False
SubGameSelectCount_Athena=2
SubGameLastSelectedTime_Athena=
SubGameSelectCount_Campaign=0
SubGameLastSelectedTime_Campaign=0001.01.01-00.00.00
LastTimeSettingsSnapshotUploaded=0001.01.01-00.00.00
LastTimeLockerPresetCountUploaded=
FirstLoginOnDevice=
SafeZone=1.000000
bIsSafeZoneSet=False
CachedPlayerLevel=0
bShowActorsWithSeasonItemTagMapIndicators=True
CachedBattleStars=0
CachedAlienStylePoints=0
CachedStylePoints=0
CachedClaimableRewards=()
CachedHighestBattlePassUnlockedPage=1
bShowCareerShowcaseTabBang=False
bArmASREnabled=False
CustomVoiceChatInputDevice=
CustomVoiceChatOutputDevice=
CustomVoiceChatInputDeviceId=
CustomVoiceChatOutputDeviceId=
bMotionBlur=False
bAllowUIParallax=False
bShowGrass=False
bShowFPS=True
bUseGPUCrashDebugging=False
bStopRenderingInBackground=False
bLatencyTweak1=False
LatencyTweak2=0
bLatencyFlash=False
FortAntiAliasingMethod=Disabled
bEnableDLSSFrameGeneration=False
TemporalSuperResolutionQuality=Recommended
DLSSQuality=0
XeSSQuality=2
ArmASRQuality=1
QualcommGSRQuality=1
PotentiallyUpscaledResolutionQuality=100.000000
NeverUpscaledResolutionQuality=100.000000
bUseNanite=False
DesiredGlobalIlluminationQuality=0
DesiredReflectionQuality=0
PreNaniteGlobalIlluminationQuality=1
PreNaniteReflectionQuality=1
bRayTracing=False
b120FpsMode=False
FrontendFrameRateLimit=120
bIsEnergySavingEnabledIdle=False
bIsEnergySavingEnabledFocusLoss=False
EnergySavingLevelFocusLoss=1
DisplayGamma=2.700000
UserInterfaceContrast=1.000000
NamedTimes=()
NamedCounts=(("lastfrontendflow_Fortnite", 40),("lastfrontendflow_Fortnite_HotfixVer", 0),("UEnableMultiFactorModal::ShouldShowMFASplashScreen", 40),("UEnableMultiFactorModal::ShouldShowMFASplashScreen_HotfixVer", 0))
BattlePassOverrideTracker=0
NewestProgressiveCosmeticSetSeen=
CurrentLockerSortsByTag=()
CurrentLockerFiltersByTag=()
ArchetypeShuffleSelectionBias=()
bLockerHideUnsupportedItems=False
bLockerSortItemsByRelevance=True
bHasUsedBattlePassCrewUpsellNavButton=False
LastExpectedShopRefreshTime=
bHasSeenItemShop=True
AboutShopModalVersionSeen=-1
HasSeenAboutItemModalTypes=()
bHasSeenJunoOutfitsFTUE=True
JunoFTUEQuestTrackingDisabledVersion=0
bHasSeenDonutShopSequence=True
DonutIdleGameHighScore=0.000000
RowIdToOfferSeenLevel=()
LastSelectedIsland=()
LastPlayedIsland=()
LastSelectedPlaylist=()
LastSelectedFillOption=True
bLastSelectedPrivateMatchOption=False
CustomMatchOptions=()
CreativeOptions=()
bHasSeenCreativePhoneTutorial=True
bHasSeenCreativeHeatmapTutorial=True
CreativeOptionLastUsedCategory=0
CreativeOptionLastUsedIndexInCategory=0
LastSelectedChildActivityMap=()
ClamOneDMVersion=1
ClamOneDMPreviousVersion=1
ClamOneDMMaxEvents=200
LastNewsVersionViewedBR=
LastNewsVersionViewedCreative=
LastNewsVersionViewedSTW=
LastPRMEtag=
LastFrontEndBackPlateStageUsed[0]=season4000
LastFrontEndBackPlateStageUsed[1]=default
bEulaAccepted=True
EulaAcceptedUserId=
LastEulaCheckTime=
EulaCacheVersion=1
HUDLayoutData[0]=(LayoutEntries=)
HUDLayoutData[1]=(LayoutEntries=)
HUDLayoutData[2]=(LayoutEntries=)
bHasBeenNotifiedAboutLegacyLayoutDeprecation=True
ActiveHUDProfileIdentifier=(HUDProfileType=(TagName=""),Guid=00000000000000000000000000000000)
bHasSeenTapToShoot=True
NumTimesSeeingPanningTip=0
FireModeData=(bAutoFireIsEnabled=True,b3DTouchEnabled=False,bTapToShootEnabled=False,bAlwaysShowDedicatedButton=True,FireModeType=Unset)
SimpleMobileStats=()
AudioOutputDeviceId=
bUseHeadphoneMode=False
InitialBenchmarkState=1
bDisableMouseAcceleration=False
ChosenLoginType=None
SocialImportOptedOutVersion=0
VKImportOptedOutVersion=0
bHasSeenErebusSocialImport=True
bHasSeenFriendImportToast=True
LastSocialImportPromptTime=0001.01.01-00.00.00
bAutoImportFriendEnabled=False
bSeenLetoSellModal=False
SocialImportPromptCountCurrentVersion=0
SocialImportPromptCountAllVersions=0
VKImportPromptCountCurrentVersion=0
VKImportPromptCountAllVersions=0
LastAccountItemWarningTime=0001.01.01-00.00.00
bMultiFactorAuthModalOpOut=False
LastEnableMFAModalPromptTime=0001.01.01-00.00.00
LastVKImportPromptTime=0001.01.01-00.00.00
LastAffiliateToastTime=0001.01.01-00.00.00
FailedInviteMap=()
MobileRecommendationDismissedVersion=0
ShowLiveStreamPictureInPictureInMatchV2=Default
CurrentLivePiPStreamOverrideCounter=0
SelectedFrontEnd=
bNeverShowMobileLink=True
bHasMigratedDownloadSettings=False
bSendAppsFlyerEventOnInstallation=True
bAllowFullGameDownload=False
ReducedDataUsage=UnSet
bAllowCellularDownload=False
LastAutoDownloadHighResTextureReminder=639097902858560000
bOverrideMobileScalabilityForNewUser=False
bShouldTryShowMobileDefaultSettingsChanged=False
bAutoLaunchFullGame=False
bAllowDownloadHighResMips=False
ContentQualityLevelSelected=Unset
TextureQualityLevel=UnSet
bAllowLowPowerMode=False
bAllowVideoPlayback=True
MobileFPSMode=Mode_30Fps
MobileQualitySettingsResetDefaultsGUID=
bHasSeenSamsungPressureSensorWarning=True
bNeverDisplaySamsungPressureSensorWarning=True
bHasRecentlySeenBadMatchPopup=True
MatchesSinceLastBadMatchPopup=0
bHasAlreadyRatedOnGooglePlay=True
DaysToSnoozeBeforeNextGooglePlayRating=0
GooglePlayRatingDelayedOccurences=0
ParsleyIdleTime=Never
bShowTemperature=False
LastGameStartNotificationSentTime=0001.01.01-00.00.00
LastYearForcedDisplayWinterfestInfoButton=0
LastYearWinterfestWasSeen=0
bHasSeenSidekickWelcomePopup=True
bHasSeenLobbyModeSetNotification=True
bHasSeenLobbyModeChangedNotification=True
bHasSeenDiscoveryDetailsModeSetNotification=True
bHasSeenDiscoveryCCUModal=True
bHasSeenCreatorPageFirstTimeTooltip=True
LowInputLatencyModeIsEnabled=True
bNeedsToSeeFireModeSelectionReminder=False
MatchesSinceInitialFireModeSelection=0
bIsChatNotificationSettingInitialized=False
LastLaunchPushNotificationState=NotSet
bIsPushNotificationConsentValid=False
GlobalConfigData=()
bUseVSync=False
bUseDynamicResolution=False
ResolutionSizeX=
ResolutionSizeY=
LastUserConfirmedResolutionSizeX=
LastUserConfirmedResolutionSizeY=
LastConfirmedFullscreenMode=0
PreferredFullscreenMode=0
DisplayID=
DisplayIndex=-1
LastUserConfirmedDisplayID=
LastUserConfirmedDisplayIndex=-1
AudioQualityLevel=1
LastConfirmedAudioQualityLevel=1
FrameRateLimit=
DesiredScreenWidth=
DesiredScreenHeight=
LastUserConfirmedDesiredScreenWidth=
LastUserConfirmedDesiredScreenHeight=
LastRecommendedScreenWidth=-1.000000
LastRecommendedScreenHeight=-1.000000
LastCPUBenchmarkResult=-1.000000
LastGPUBenchmarkResult=-1.000000
LastGPUBenchmarkMultiplier=1.000000
bUseHDRDisplayOutput=False
HDRDisplayOutputNits=1000
RecentSelections=()

[ScalabilityGroups]
sg.ResolutionQuality=100
sg.ViewDistanceQuality=0
sg.AntiAliasingQuality=0
sg.ShadowQuality=0
sg.GlobalIlluminationQuality=0
sg.ReflectionQuality=0
sg.PostProcessQuality=0
sg.TextureQuality=0
sg.EffectsQuality=0
sg.FoliageQuality=0
sg.ShadingQuality=0
sg.LandscapeQuality=0

[D3DRHIPreference]
PreferredRHI=dx12
PreferredFeatureLevel=es31